# Air configuration file for live reloading
root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = "go build -o ./tmp/main ."
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "tmp", "assets"]
  exclude_file = ["*.md"]
  stop_on_error = true
  delay = 100

[log]
  level = "debug"
  format = "text"

[screen]
  clear = true
